mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('wenyan/',include('wenyan.urls')),
    path('admin/', admin.site.urls),
]

wenyan/urls.py
from django.urls import path

from . import views,newviews

app_name='wenyan'
urlpatterns = [
    path('', views.index, name='index'),
    path('search_result/',views.search_result,name='search_result'),
    path('word/<str:word>/',views.word,name='word'),
    path('edit_explanation/<str:word>/',views.edit_explanation,name='edit_explanation'),
    path('submit_explanation/<int:word_id>',views.submit_explanation,name='submit_explanation'),
    path('edit_sentence/<int:explanation_id>',views.edit_sentence,name="edit_sentence"),
    path('submit_sentence/<int:explanation_id>',views.submit_sentence,name="submit_sentence"),
    path('index_tips/',views.index_tips,name="index_tips"),
    path('sentence_tips/',views.sentence_tips,name="sentence_tips"),
    path('id2info/',views.id2info,name="id2info"),
    path('chuchu_tips/',views.chuchu_tips,name="chuchu_tips"),
    path('delete_example/',views.delete_example,name="delete_example"),
    path('delete_explanation/',views.delete_explanation,name="delete_explanation"),

    path('contest/',newviews.Mainpage,name="contest_mp"),
    path('contest_hy/',newviews.Mainpage_hy,name="contest_hy_mp"),
    path('contest/exercise/',newviews.ExercisePage, name="contest_ep"),
    path('contest/test/',newviews.TestPage,name="contest_tp"),
    path('contest/answer/',newviews.AnswerPage,name="contest_ap"),
]

wenyan/models.py
from django.db import models

# Create your models here.
MAXLEN=150

class Word(models.Model):
    word_text=models.CharField(max_length=MAXLEN)
    def __str__(self):
        return self.word_text

class Explanation(models.Model):
    PART_OF_SPEECH=['形容词','副词','名词','动词','介词','连词','代词','助词','数词','量词','其它']
    word=models.ForeignKey(Word,on_delete=models.CASCADE,null=True)
    explanation_text=models.CharField(max_length=MAXLEN)
    part_of_speech=models.CharField(max_length=3)
    gu_jin=models.BooleanField(default=False)
    def __str__(self):
        return self.explanation_text

class Chuchu(models.Model):
    chuchu_text=models.CharField(max_length=MAXLEN)
    def __str__(self):
        return self.chuchu_text

class Sentence(models.Model):
    JUSHI=['无特殊句式','判断句','省略句','被动句','定语后置句','宾语前置句','主谓倒装句','介词结构后置句']
    sentence_text=models.CharField(max_length=MAXLEN)
    jushi=models.CharField(max_length=7)
    # chuchu=models.CharField(max_length=MAXLEN)
    chuchu=models.ForeignKey(Chuchu,on_delete=models.CASCADE,null=True) # 这个CASCADE不会真正被触发，为了避免报错而写了CASCADE（实际上仅仅表示关联而不表示从属）
    def __str__(self):
        return self.sentence_text

class Example(models.Model):
    LIVE_USE=['无词类活用','形容词作名词','形容词作动词','意动用法','使动用法','名词作形容词','名词作状语','名词作动词','动词作名词']
    explanation=models.ForeignKey(Explanation,on_delete=models.CASCADE,null=True)
    sentence=models.ForeignKey(Sentence,on_delete=models.CASCADE,null=True) # 这个CASCADE不会真正被触发，为了避免报错而写了CASCADE（实际上仅仅表示关联而不表示从属）
    live_use=models.CharField(max_length=6)
    def __str__(self):
        return self.sentence.sentence_text+" -> "+self.explanation.word.word_text+"("+self.explanation.explanation_text+")"

class Tongjia(models.Model):
    sentence=models.ForeignKey(Sentence,on_delete=models.CASCADE,null=True)
    before=models.CharField(max_length=MAXLEN)
    after=models.CharField(max_length=MAXLEN)
    def __str__(self):
        return self.before+' 同 '+self.after

class Appear(models.Model):
    example=models.ForeignKey(Example,on_delete=models.CASCADE,null=True)
    appear_begin=models.IntegerField()
    appear_end=models.IntegerField()
    def __str__(self):
        return '['+str(self.appear_begin)+','+str(self.appear_end)+')'

class Example_live_use(models.Model):
    example=models.ForeignKey(Example,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.example.sentence.sentence_text

class Sentence_jushi(models.Model):
    sentence=models.ForeignKey(Sentence,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.sentence.sentence_text

class Visit(models.Model):
    visit_score=models.FloatField()
    def __str__(self):
        return '成绩：'+str(self.visit_score)

wenyan/views.py
# Create your views here.
import json
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.urls import reverse

from .models import *

def index(request):
    return render(request,'wenyan/index.html',{})

def search_result(request):
    return HttpResponseRedirect(reverse('wenyan:word',args=(request.GET['search'],)))

def word(request,word):
    context={}
    try:
        search_word=Word.objects.get(word_text=word)
    except Word.DoesNotExist:
        context={
            'word_text':word,
        }
    else:
        context={
            'word':search_word,
            'word_text':word,
        }
    return render(request,'wenyan/word.html',context)

def edit_explanation(request,word):
    edit_word=None
    try:
        edit_word=Word.objects.get(word_text=word)
    except Word.DoesNotExist:
        edit_word=Word(word_text=word)
        edit_word.save()
    context={
        'word':edit_word,
        'part_of_speech_options':Explanation.PART_OF_SPEECH,
    }
    return render(request,'wenyan/edit_explanation.html',context)

def submit_explanation(request,word_id):
    word_stored=get_object_or_404(Word,pk=word_id)
    word_stored.explanation_set.create(
        explanation_text=request.POST['explanation_text'],
        part_of_speech=request.POST['part_of_speech'],
        gu_jin=(request.POST.get('gu_jin')=='gu_jin'),
    )
    return HttpResponseRedirect(reverse('wenyan:edit_explanation',args=(word_stored.word_text,)))

def edit_sentence(request,explanation_id):
    explanation=Explanation.objects.get(pk=explanation_id)
    context={
        'word_text':explanation.word.word_text,
        'explanation':explanation,
        'live_use_options':Example.LIVE_USE,
        'jushi_options':Sentence.JUSHI,
    }
    return render(request,'wenyan/edit_sentence.html',context)

def submit_sentence(request,explanation_id):
    explanation_stored=get_object_or_404(Explanation,pk=explanation_id)

    # 是否已经存储了该chuchu
    POST_chuchu=request.POST.get('chuchu')
    chuchu=None
    try:
        chuchu=Chuchu.objects.get(chuchu_text=POST_chuchu)
    except Chuchu.DoesNotExist:
        chuchu=Chuchu(chuchu_text=POST_chuchu)
        chuchu.save()

    # 是否已经存储了该sentence
    sentence_stored=None
    original_jushi=None
    current_jushi=request.POST.get('jushi')
    POST_sentence_text=request.POST.get('sentence_text')
    try:
        sentence_stored=Sentence.objects.get(sentence_text=POST_sentence_text)
        original_jushi=sentence_stored.jushi
    except Sentence.DoesNotExist:
        sentence_stored=Sentence()

    # 更新sentence
    sentence_stored.sentence_text=POST_sentence_text
    sentence_stored.jushi=current_jushi
    sentence_stored.chuchu=chuchu
    sentence_stored.save()

    # 更新sentence_jushi
    if ((not original_jushi) or original_jushi=="无特殊句式") and current_jushi!="无特殊句式":
        # 1. original_jushi=None
        #    这是一句新加入的例句，并且有特殊句式
        # 2. original_jushi="无特殊句式"
        #    原先错误地判断为无特殊句式，现在经过更改，有特殊句式
        sentence_stored.sentence_jushi_set.create()
    elif original_jushi!="无特殊句式" and current_jushi=="无特殊句式":
        # 原先错误地判断为有特殊句式，现在经过更改，无特殊句式
        for sentence_jushi in sentence_stored.sentence_jushi_set.all(): # 实际上应该只循环一次
            sentence_jushi.delete()

    # 更新tongjia
    for tongjia in sentence_stored.tongjia_set.all():
        tongjia.delete()
    POST_before,POST_after=request.POST.getlist('before'),request.POST.getlist('after')
    for i in range(int(request.POST['tongjia_count'])):
        sentence_stored.tongjia_set.create(before=POST_before[i],after=POST_after[i])
    
    # 添加example
    POST_live_use=request.POST.get('live_use')
    example=explanation_stored.example_set.create(
        sentence=sentence_stored,
        live_use=POST_live_use,
    )

    # 添加example_live_use
    if POST_live_use!="无词类活用":
        example.example_live_use_set.create()
    
    # 为example添加appear
    for begin_end in request.POST.getlist('appear_pos'):
        tmp_pair=begin_end.split('-')
        example.appear_set.create(appear_begin=int(tmp_pair[0]),appear_end=int(tmp_pair[1]))
    
    return HttpResponseRedirect(reverse('wenyan:edit_sentence',args=(explanation_id,)))

def index_tips(request):
    part=request.POST.get('search_part')
    tips=[word.word_text for word in Word.objects.filter(word_text__contains=part)]
    return JsonResponse({"data":tips[-5:],"code":200,},json_dumps_params={'ensure_ascii':False})

def sentence_tips(request):
    part=request.POST.get('sentence_part')
    tips=[{"text":sentence.sentence_text,"id":sentence.id} for sentence in Sentence.objects.filter(sentence_text__contains=part)]
    return JsonResponse({"data":tips[-5:],"code":200,},json_dumps_params={'ensure_ascii':False})

def id2info(request):
    """
    通过sentence_tips的<li>元素的id找到对应的sentence
    并将它的信息填入表单
    """
    sentence_id=request.POST.get('sentence_id') # 这里不需要转换成int
    sentence=Sentence.objects.get(id=sentence_id)
    tips={
        "jushi":sentence.jushi,
        "chuchu":sentence.chuchu.chuchu_text,
        "tongjia":[{"before":tj.before,"after":tj.after} for tj in sentence.tongjia_set.all()],
    }
    print("Encounter: ",sentence.sentence_text)
    return JsonResponse({"data":tips,"code":200,},json_dumps_params={'ensure_ascii':False})

def chuchu_tips(request):
    part=request.POST.get('chuchu_part')
    tips=[chuchu.chuchu_text for chuchu in Chuchu.objects.filter(chuchu_text__contains=part)]
    return JsonResponse({"data":tips[-5:],"code":200,},json_dumps_params={'ensure_ascii':False})

def delete_example(request):
    example=get_object_or_404(Example,id=request.POST.get('example_id'))
    explanation_id=example.explanation.id
    example.delete()
    return HttpResponseRedirect(reverse('wenyan:edit_sentence',args=(explanation_id,)))

def delete_explanation(request):
    explanation=get_object_or_404(Explanation,id=request.POST.get('explanation_id'))
    word=explanation.word.word_text
    explanation.delete()
    return HttpResponseRedirect(reverse('wenyan:edit_explanation',args=(word,)))

wenyan/templates/wenyan/AnswerPage.html
<!DOCTYPE html>
<html>
    <head >
        {% load static %}
        {% load wenyan_extras %}
        {% favicon %}
        <meta charset="UTF-8" />
        <title>文言文答题</title>
        <link rel="stylesheet" type="text/css" href="{% static 'wenyan/ap.css' %}">
    </head>
    <body >
        <div id="a1">
            <a href="{% url 'index' %}" title="关于我们" id="a11">主页</a>
            <a href="{% url 'wenyan:index' %}" title="来学文言文吧" id="a11">字典</a>
            <a href="{% url 'wenyan:contest_mp' %}" title="休息一会儿" id="a12">退出</a>
            <div id="cnt">{{avr}} {{now}}/{{allnum}}</div>
        </div>
        <div id="a2">
            <div id="type">单项选择题：</div>
            <p id="qst">{{question}}</p>
            <p id="txt">
                {% for text_sent in text %}{{forloop.counter}}. {% if nowtype == 4 %} {{text_sent|highlight}} {% else %}{{text_sent}}{% endif %}<br> {% endfor %}
            </p>
            <form>
                <div id="A"><div id="a23">A.</div><div id="a21">{{choice.0}}</div><input type="radio" readonly {% if choose == 'A' %} checked {% endif %} disabled name="ques" value="A" class="liRight" /></div>
                <div id="B"><div id="a23">B.</div><div id="a21">{{choice.1}}</div><input type="radio" readonly {% if choose == 'B' %} checked {% endif %} disabled name="ques" value="B" class="liRight" /></div>
                <div id="C"><div id="a23">C.</div><div id="a21">{{choice.2}}</div><input type="radio" readonly {% if choose == 'C' %} checked {% endif %} disabled name="ques" value="C" class="liRight" /></div>
                <div id="D"><div id="a23">D.</div><div id="a21">{{choice.3}}</div><input type="radio" readonly {% if choose == 'D' %} checked {% endif %} disabled name="ques" value="D" class="liRight" /></div>
            </form>
        </div>
        <div id="a5">
        {% if correct %}
            <img src="{% static '/wenyan/img/true.png' %}">
            <div id="a51">回答正确</div>
            <div id="a52">+{{defen}}分</div>
        {% else %}
            <img src="{% static '/wenyan/img/false.png' %}">
            <div id="a53">回答错误</div>
            <div id="a54">+{{defen}}分</div>
        {% endif %}
        </div>
        <div id="a3">
            <span id="a31"><b>解析：</b></span><br>
            答案是{{ans}}。
            {% for eachreason in reason %}
                第{{forloop.counter}}句:{% for everyreason in eachreason %} {{everyreason}}; {% endfor %}
            {% endfor %}
        </div>
        <form action="{% url 'wenyan:contest_tp' %}" method="post">
        {% csrf_token%}
        <div id="a4">
            <input type='submit' name="indicate" id="a41" value="上一题">
            <input type='submit' name="indicate" id="a42" value="结束测试">
            <input type='submit' name="indicate" id="a43" value="下一题">
            <input type='hidden' name='cnt' value="{{now}}">
            <input type='hidden' name='score' value="{{score}}">
            <input type='hidden' name='lianxu' value="{{lianxu}}">
            <input type='hidden' name='mx' value="{{allnum}}">
        </div>
        </form>
    </body>
</html>

wenyan/templates/wenyan/AnswerPage2.html
<!DOCTYPE html>
<html>
    <head >
        {% load static %}
        {% load wenyan_extras %}
        {% favicon %}
        <meta charset="UTF-8" />
        <title>文言文答题</title>
        <link rel="stylesheet" type="text/css" href="{% static 'wenyan/ap.css' %}">
    </head>
    <body >
        <div id="a1">
            <a href="{% url 'index' %}" title="关于我们" id="a11">主页</a>
            <a href="{% url 'wenyan:index' %}" title="来学文言文吧" id="a11">字典</a>
            <a href="{% url 'wenyan:contest_mp' %}" title="休息一会儿" id="a12">退出</a>
            <div id="cnt">{{avr}} {{now}}/{{allnum}}</div>
        </div>
        <div id="a2">
            <div id="type">单项选择题：</div>
            <p id="qst">{{question}}</p>
            <p id="txt">
                {% for text_sent in text %}{{forloop.counter}}. {% if nowtype == 4 %} {{text_sent|highlight}} {% else %}{{text_sent}}{% endif %}<br> {% endfor %}
            </p>
            <form>
                <div id="A"><div id="a23">A.</div><div id="a21">{{choice.0}}</div><input type="radio" readonly {% if choose == 'A' %} checked {% endif %} disabled name="ques" value="A" class="liRight" /></div>
                <div id="B"><div id="a23">B.</div><div id="a21">{{choice.1}}</div><input type="radio" readonly {% if choose == 'B' %} checked {% endif %} disabled name="ques" value="B" class="liRight" /></div>
                <div id="C"><div id="a23">C.</div><div id="a21">{{choice.2}}</div><input type="radio" readonly {% if choose == 'C' %} checked {% endif %} disabled name="ques" value="C" class="liRight" /></div>
                <div id="D"><div id="a23">D.</div><div id="a21">{{choice.3}}</div><input type="radio" readonly {% if choose == 'D' %} checked {% endif %} disabled name="ques" value="D" class="liRight" /></div>
            </form>
        </div>
        <div id="a5">
        {% if correct %}
            <img src="{% static '/wenyan/img/true.png' %}">
            <div id="a51">回答正确</div>
            <div id="a52">+{{defen}}分</div>
        {% else %}
            <img src="{% static '/wenyan/img/false.png' %}">
            <div id="a53">回答错误</div>
            <div id="a54">+{{defen}}分</div>
        {% endif %}
        </div>
        <div id="a3">
            <span id="a31"><b>解析：</b></span><br>
            答案是{{ans}}。
            {% for eachreason in reason %}
                第{{forloop.counter}}句:{% for everyreason in eachreason %} {{everyreason}}; {% endfor %}
            {% endfor %}
        </div>
        <form action="{% url 'wenyan:contest_ap' %}" method="post">
        {% csrf_token%}
        <div id="a4">
            <input type='submit' name="indicate" id="a41" value="上一题">
            <input type='submit' name="indicate" id="a43" value="下一题">
            <input type='hidden' name='cnt' value="{{now}}">
            <input type='hidden' name='score' value="{{score}}">
            <input type='hidden' name='lianxu' value="{{lianxu}}">
            <input type='hidden' name='mx' value="{{allnum}}">
        </div>
        </form>
    </body>
</html>

wenyan/templates/wenyan/ScorePage.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        {% load wenyan_extras %}
        {% favicon %}
        <meta charset="UTF-8" />
        <title>文言文答题</title>
        <link rel="stylesheet" type="text/css" href="{% static 'wenyan/sp.css' %}">
        <style type="text/css">
            a:hover{font-weight: bold;}
        </style>
    </head>
    <body >
        <div id="a1">
            <a href="{% url 'index' %}" title="关于我们" id="a11">主页</a>
            <a href="{% url 'wenyan:index' %}" title="来学文言文吧" id="a11">字典</a>
            <a href="{% url 'wenyan:contest_mp' %}" title="休息一会儿" id="a12">退出</a>
        </div>
        <div id="all">
            <div id="a2">
                恭喜你，在本次测试中得到了<span id="score">{{score}}</span>分！<br>
                平均每题得到<span id="score">{{avr}}</span>分！
            </div>
            <div id="a3">
                超过了<span id="perc">{{baifenwei}}%</span>的测试者。
            </div>
        </div>
        <div id='go'>
        <form action="{% url 'wenyan:contest_ap' %}" method="post">
        {% csrf_token %}
            <input type='submit' name='indicate' id="check" value="查看题目">
            <input type='hidden' name='mx'value="{{allnum}}">
            <input type="hidden" name="avr" value="{{avr}}">
            <input type="hidden" name="score" value="{{score}}">
        </form>
        <form action="{% url 'wenyan:contest_tp' %}" method="post">
        {% csrf_token %}
            <input type='submit' name='indicate' id="redo" value="再来一次">
        </form>
        <form action="{% url 'wenyan:contest_mp' %}" method="post">
        {% csrf_token %}
            <input type='submit' name='indicate' id="quit" value="残忍退出">
        </form>
        </div>
        <div id="rest">
            <div id="a4">
                ——就算是万丈深渊，跳下去，也是前程万里！
            </div>
            <div id="pic"> <img src="{% static 'wenyan/img/kona.jpg' %}" alt="Something wrong!" height=300px width=480px></div>
        </div>
    </body>
</html>

wenyan/templates/wenyan/edit_explanation.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
{% load wenyan_extras %}
    <meta charset="utf-8">
    {% favicon %}
    <title>在线文言文字典</title>
    <link rel="stylesheet" href="{% static 'wenyan/edit_explanation.css' %}">
</head>
<body>
    <div id="topOfTheWorld">
        <ul id="naviBar">
            <li class="naviLink"><a class="topA" href="{% url 'index' %}">主页</a></li>
            <li class="naviLink"><a class="topA" href="{% url 'wenyan:contest_mp' %}">答题</a></li>
            <li class="naviLink"><a class="topA" href="{% url 'wenyan:index' %}">字典</a></li>
            <li class="naviRLink"><a class="topA" href="{% url 'wenyan:word' word.word_text %}">返回</a></li>
        </ul>
    </div>
    <p id="word">编辑——{{word.word_text}}</p>
{% for explanation in word.explanation_set.all %}
    <div>
        <div class="explanationWrap">
            <p class="explanationItem">
                [{{explanation.part_of_speech}}]&emsp;{{explanation.explanation_text}}
            </p>
            <p class="explanationOption">
                <a class="editSentence" href="{% url 'wenyan:edit_sentence' explanation.id %}">编辑例句</a>
            </p>
            <p class="explanationOption explanationDelete">删除</p>
        </div>
        <form class="deleteConf" action="{% url 'wenyan:delete_explanation' %}" method="post">
        {% csrf_token %}
            <p>确定要删除此义项吗？</p>
            <input name="explanation_id" type="hidden" value="{{explanation.id}}">
            <div class="buttonWrap">
                <button type="button" class="darkButton deleteCancel">取消</button>
                <button type="submit" class="darkButton">确定</button>
            </div>
        </form>
    </div>
{% endfor %}
    <div class="explanationWrap" id="addExplanation">
        <p class="explanationItem">添加义项...</p>
    </div>
    <div id="formWrap">
        <form action="{% url 'wenyan:submit_explanation' word.id %}" method="post">
        {% csrf_token %}
            <p>词性：
            <select name="part_of_speech">
            {% for choice in part_of_speech_options %}
                <option value="{{choice}}">{{choice}}</option>
            {% endfor %}
            </select>
            </p>
            <label>古今异义<input class="checkboxInput" type="checkbox" name="gu_jin" value="gu_jin"></label>
            <p>解释：<input class="textInput" name="explanation_text" type="text" required></p>
            <div class="buttonWrap">
                <button type="button" id="backButton" class="darkButton">取消</button>
                <button type="submit" class="darkButton">确定</button>
            </div>
        </form>
    </div>
    <script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'wenyan/edit_explanation.js' %}"></script>
</body>
</html>

wenyan/templates/wenyan/edit_sentence.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
{% load wenyan_extras %}
    <meta charset="utf-8">
    <!-- <link rel="shortcut icon" href="{% static 'wenyan/img/favicon.ico' %}" type="image/x-icon"> -->
    {% favicon %}
    <title>在线文言文字典</title>
    <link rel="stylesheet" href="{% static 'wenyan/edit_sentence.css' %}">
</head>
<body>
    <div id="topOfTheWorld">
        <ul id="naviBar">
            <li class="naviLink"><a class="topA" href="{% url 'index' %}">主页</a></li>
            <li class="naviLink"><a class="topA" href="{% url 'wenyan:contest_mp' %}">答题</a></li>
            <li class="naviLink"><a class="topA" href="{% url 'wenyan:index' %}">字典</a></li>
            <li class="naviRLink"><a class="topA" href="{% url 'wenyan:edit_explanation' word_text %}">返回</a></li>
        </ul>
    </div>
    <p id="word">编辑例句——{{word_text}}</p>
    <p id="explanation">[{{explanation.part_of_speech}}]{{explanation.explanation_text}}</p>
{% for example in explanation.example_set.all %}
    <div>
        <div class="sentenceWrap">
            <input type="hidden" class="exampleId" val="{{example.id}}">
            <p class="sentenceItem">
                {{example|highlight}}——{{example.sentence.chuchu.chuchu_text}}
            </p>
            <p class="sentenceOption sentenceDelete">删除</p>
        </div>
        <form class="deleteConf" action="{% url 'wenyan:delete_example' %}" method="post">
        {% csrf_token %}
            <p>确定要删除此例句吗？</p>
            <input name="example_id" type="hidden" value="{{example.id}}">
            <div class="buttonWrap">
                <button type="button" class="darkButton deleteCancel">取消</button>
                <button type="submit" class="darkButton">确定</button>
            </div>
        </form>
    </div>
{% endfor %}
    <div class="sentenceWrap" id="addSentence">
        <p class="sentenceItem">添加例句...</p>
    </div>
    <div id="formWrap">
        <form action="{% url 'wenyan:submit_sentence' explanation.id %}" method="post">
        {% csrf_token %}
            <input type="hidden" value="{{word_text}}" id="word_text">
            <div id="sentence_and_tips">
                例句内容：<input class="textInput" type="text" name="sentence_text" id="sentence_text" required>
                <ul id="sentence_tips"></ul>
            </div>
            <p id="appear_choice"></p>
            <p>本例句中“{{word_text}}”的词类活用：
                <select name="live_use">
                {% for choice in live_use_options %}
                    <option value="{{choice}}">{{choice}}</option>
                {% endfor %}
                </select>
            </p>
            <p>特殊句式：
                <select name="jushi" id="jushi">
                {% for choice in jushi_options %}
                    <option value="{{choice}}">{{choice}}</option>
                {% endfor %}
                </select>
            </p>
            <p>例句中包含<input type="text" class="textInput shortInput" name="tongjia_count" id="tongjia_count" value="0" required>个通假字</p>
            <p id="tongjia_input"></p>
            <div id="chuchu_and_tips">
                出处：<input class="textInput" type="text" name="chuchu" id="chuchu" required>
                <ul id="chuchu_tips"></ul>
            </div>
            <div class="buttonWrap">
                <button type="button" id="backButton" class="darkButton">取消</button>
                <button type="submit" class="darkButton">确定</button>
            </div>
        </form>
    </div>
    <script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'wenyan/edit_sentence.js' %}"></script>
    <script>
        $.ajaxSetup({
            headers:{"X-CSRFTOKEN": "{{csrf_token}}"},
        })
    </script>
</body>
</html>

wenyan/templates/wenyan/frontpage.html
<!DOCTYPE html>
<html>
    <head>
	{% load static %}
        {% load wenyan_extras %}
        {% favicon %}
        <meta charset="UTF-8" />
        <title>文言文答题</title>
        <link rel="stylesheet" type="text/css" href="{% static 'wenyan/fp.css' %}">
        <style type="text/css">
            a:hover{font-weight: bold;}
        </style>
    </head>
    <body >
        <div id="a1">
            <a href="{% url 'index' %}" title="关于我们" id="a11">主页</a>
            <a href="{% url 'wenyan:index' %}" title="来学文言文吧" id="a11">字典</a>
            <a href="{% url 'wenyan:contest_hy_mp' %}" title="甘雨贴贴(≧∇≦)ﾉ" id="a12">护眼</a>
        </div>
        <div id="a2">
            <b>文言文答题模块</b>
        </div>
        <div id="a3">
            <a href="{% url 'wenyan:contest_tp' %}" title="开始答题！" id="start">开始答题</a>
        </div>
        <div id="a4">
            <a href="{% url 'wenyan:contest_ep' %}" title="练习一下吧(～￣▽￣)～" id="prac">自由练习</a>
        </div>
    </body>
</html>